name: Python package
on:
  push:    
    tags:        
      - "v*.*.*"
    branches: [master, main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.12
        with:
          cmake-version: '3.16.x'
      - name: Use cmake
        run: cmake --version
      
      - uses: actions/checkout@v2
      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v1.10
        with:
          pypi_token: ${{ secrets.PYPI_TOKEN }}
          extra_build_dependency_packages: "libblas3 liblapack3 liblapack-dev libblas-dev gfortran"
